version: '2.0'
services:
  neo4j:
    image: neo4j:3.1
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./data/neo4j:/data"
      - "./data/import:/var/lib/neo4j/import"
      - "./data/plugins:/var/lib/neo4j/plugins"
    environment:
      - NEO4J_AUTH=none
