namenode:
    image: gelog/hadoop:2.6.0
    ports: 
        - "50070:50070"
    volumes:
        - ./namenode/data:/data
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: gelog/hadoop
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "50075"
    volumes:
        - ./datanode/data:/data
    command: hdfs datanode
    hostname: hdfs-datanode
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: gelog/hadoop
    ports:
        - "50090:50090"
    volumes:
        - ./secondarynamenode/data:/data
    command: hdfs secondarynamenode
    links:
        - namenode:hdfs-namenode

yarn:
    image: gelog/hadoop
    ports:
        - "8088:8088"
        - "8042:8042"
    volumes:
        - ./yarn/data:/data
    command: start-yarn.sh
    hostname: yarn
    links:
        - namenode:hdfs-namenode
        - datanode:hdfs-datanode
