version: '2.0'
services:
  influxdb:
    image: influxdb:alpine
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
#    environment:
#      - INFLUXDB_GRAPHITE_ENABLED=true
